### ISSUE TITLE
jquery ajax with useFakeTimers and autoRespond 

### ISSUE THREAD

**Issue by icholy** [cjohansen/Sinon.JS#285]
`jQuery.ajax` doesn't work with `useFakeTimers` and `autoRespond` [jsfiddle](http://jsfiddle.net/gMk4f/1/)

``` javascript
var xhr = sinon.fakeServer.create();
var clock = sinon.useFakeTimers();
xhr.autoRespond = true;
xhr.respondWith(alert.bind(null, "Does Not Work"));
$.getJSON("/foo");
// xhr.respond();
```

works without `autoRespond`

``` javascript
var xhr = sinon.fakeServer.create();
var clock = sinon.useFakeTimers();
// xhr.autoRespond = true;
xhr.respondWith(alert.bind(null, "Without autoRespond Works"));
$.getJSON("/foo");
xhr.respond();
```

works without `useFakeTimers`

``` javascript
var xhr = sinon.fakeServer.create();
// var clock = sinon.useFakeTimers();
xhr.autoRespond = true;
xhr.respondWith(alert.bind(null, "Without Clock Works"));
$.getJSON("/foo");
// xhr.respond();
```

Is there a way to get this to work? I'm using `1.7.1`

**Comment by freethejazz** [comment]
@cjohansen The problem exists because autoRespond depends on `setTimeout` to work properly. When fake timers are in play, the server will never respond because of this line:
https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_server.js#L106
`setTimeout` here would be referring to a fake clock, and would need to be followed by `clock.tick(10) `, as @mantoni suggested, in order to actually be called.

My initial thought was to cache the native `setTimeout` and explicitly use the unmodified one here. This become tricky though, because if the user specifically chose to use fake timers, that behavior may surprise them based on expectations.

I suspect that the actual use case that @icholy was trying to accomplish was to use AJAX and some timers within a test case. It's made clear in the docs that `request.autoRespond` isn't [sufficient for testing](http://sinonjs.org/docs/#auto-respond), but `server.autoRespond` doesn't have the same caveat, so I think he/she may have been using it under some false assumptions. I had the same assumptions and experienced an issue with using autoRespond in tests, which how I came across this issue.

I would propose a fix that is two-fold:
1. Add a new configurable property along the lines of `server.respondImmediately` that provides a synchronous, automatic server response suitable for test cases.
2. Add wording in the docs about `server.autoRespond` being insufficient for testing purposes and to use the new property instead.

Thoughts?

**Comment by freethejazz** [comment]
An alternative to the second part of my proposed fix it to change the behavior of autoRespond to be synchronous unless `autoRespondAfter` is defined, but I think that might break backward compatibility.

**Comment by jq2034** [comment]
> `jQuery.ajax` doesn't work with `useFakeTimers` and `autoRespond` [jsfiddle](http://jsfiddle.net/gMk4f/1/)
> 
> ```js
> var xhr = sinon.fakeServer.create();
> var clock = sinon.useFakeTimers();
> xhr.autoRespond = true;
> xhr.respondWith(alert.bind(null, "Does Not Work"));
> $.getJSON("/foo");
> // xhr.respond();
> ```
> 
> works without `autoRespond`
> 
> ```js
> var xhr = sinon.fakeServer.create();
> var clock = sinon.useFakeTimers();
> // xhr.autoRespond = true;
> xhr.respondWith(alert.bind(null, "Without autoRespond Works"));
> $.getJSON("/foo");
> xhr.respond();
> ```
> 
> works without `useFakeTimers`
> 
> ```js
> var xhr = sinon.fakeServer.create();
> // var clock = sinon.useFakeTimers();
> xhr.autoRespond = true;
> xhr.respondWith(alert.bind(null, "Without Clock Works"));
> $.getJSON("/foo");
> // xhr.respond();
> ```
> 
> Is there a way to get this to work? I'm using `1.7.1`

https://jquerys.space/questions/using-jquery-to-verify-the-presence-of-an-element-especially-one-that-may-have-been-dynamically-inserted-via-ajax

**Comment by fatso83** [comment]
@jq2034 We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This 11 year old ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. Feel free to post the question url here, so we could follow you up over there :)

---

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
