### ISSUE TITLE
Spy on and call through a method

### ISSUE THREAD

**Issue by hypesystem** [cjohansen/Sinon.JS#668]
Jasmine has functionality for [spying on and calling through to the real version of a method](http://jasmine.github.io/2.1/introduction.html#section-Spies:_<code>and.callThrough</code>):

```javascript
spyOn(object, "method").and.callThrough();
```

This is useful in case of integration tests, where the function should run as usual, but we want to intercept the arguments it is called with.

I cannot find any similar functionality in Sinon -- am I missing something or is this case not supported? (If not, I think it would make a nice addition.)

Thank you in advance.

**Comment by hypesystem** [comment]
I looked through the API a bit more, and found a solution:

```javascript
sinon.stub(object, "method", object.method);
```

Maybe this could be covered in the documentation about stubs as a specific use case?

**Comment by cjohansen** [comment]
http://sinonjs.org/docs/#spies

**Comment by hypesystem** [comment]
@cjohansen it doesn't state how to get the same result as jasmine's `and.callThrough()`, which is what I proposed adding an example for :)

**Comment by cjohansen** [comment]
Yes it does. That is what spies are for.

> `sinon.spy` can also spy on existing functions. When doing so, the original function will behave just as normal

**Comment by blackswanny** [comment]
sinon.stub(object, "method", object.method) - looks like it returns spy instead of stub, cause it doesn't contain "returns" in chain.

**Comment by OscarGodson** [comment]
This is old and so maybe its changed but:

> When doing so, the original function will behave just as normal

Isn't what I see. 

```js
      it('calls Date with the given birth date if valid date was given', () => {
        let date = sinon.spy(global, 'Date');
        this.formatter('10/10/20');
        expect(date.calledOnce).to.be.true();
        expect(date.getCall(0).args[0]).to.be.equal('10/10/20');
      });
```

This throws an error that `Date.parse` is undefined. A method on Date that I use. However, if i simply remove `let date = sinon.spy(global, 'Date');` it works (test fails, of course, but no more JS exceptions).

In Jasmine i can do what is referenced above, `.callThrough()`

**Comment by fatso83** [comment]
@OscarGodson Your issue is only superficially related to the original issue, and deals with the fact that Sinon does not copy _static_ properties to the spy. After playing some [with a sandbox](https://codepen.io/fatso83/pen/KZXLjr?editors=1010), it seems _neither does Jasmine_!

Now I might use Jasmine wrong, but you haven't supplied code that runs standalone, so I'll just have to guess how `formatter` works (I am assuming it calls `Date.parse`). No matter if adding `callThrough`, I still need to add `date.parse = orgDate.parse;` to not crash on encountering Date.parse later on. In other words, Jasmine and Sinon seem aligned on this issue.

If you think otherwise, please supply some running code, but open a new issue as this has long since been resolved (Sinon even aquired a `callThrough` of its own in version 2).

**Comment by stevenvachon** [comment]
Sinon performs `and.callThrough()` by default. I'm actually looking for a way to prevent this but not finding anything in documentation.

**Comment by fatso83** [comment]
Yes, that's the difference between spies and stubs in Sinon.
