### ISSUE TITLE
Weird error related to iframe on Windows 7 & Firefox 26

### ISSUE THREAD

**Issue by puppypower** [cjohansen/Sinon.JS#669]
Dear Sinon guys,

I have a unit test relating to create an iframe. The unit test is working fine in Mac for whatever version of firefox, also working fine on Chrome.
However, it failed on Windows 7 & Firefox 26, and the failures are random for each running.
And I tried on Windows 7 & Firefox 35, the issue can not be reproduced anyhow.

Appreciate if you can let me know the root cause, and also the fixing if there is one.

**Comment by mroderick** [comment]
You have given us very little information to work with, I can't imagine anyone being able to figure out what the issue is from your description.

Feel free to re-open this issue with more information, see the the [guide to reporting issues](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue) for Sinon.JS.
