### ISSUE TITLE
FakeServer can't handle nested XHR

### ISSUE THREAD

**Issue by isterkebab** [cjohansen/Sinon.JS#671]
As shown here: http://jsfiddle.net/3qj20r5m/2/

Isn't this supposed to work? The inner call end up in a 404.

**Comment by gyandeeps** [comment]
It would work. What you are missing is another `this.server.respond();` statement.

check here: http://jsfiddle.net/w4yfyf2x/1/

**Comment by isterkebab** [comment]
Hi and thanks for answering.

Why isn't one `server.respond()` enough? Also, why doesn't `server.autoRespond = true` work in this case?

**Comment by gyandeeps** [comment]
Here is the answer to your question:
http://jsfiddle.net/2fu6q0xx/1/

**Comment by isterkebab** [comment]
Well, partially - you didn't answer why I need to call `server.respond()` twice ;-)

My goal is to execute the ajax calls in a synchronous manner, regardless if they're nested or not. Do I have any options but to use multiple `server.respond()` calls?

**Comment by gyandeeps** [comment]
Before you call the `server.respond()` for the first time, at that time according to [sinonjs respond() documentation](http://sinonjs.org/docs/#fakeServer) it would respond to all the resquest in the queue.

But at this moment the only call inside your quest is the call to `'/foo'`.
Your call to `'/bar'` would only gets registered when that part of code gets executed. So as of now it has not been executed yet.

Now you make the call `server.respond()` for the **first** time and it responds to all the request in the queue. Since there is only 1 request in the queue `['/foo']` it will respond to it.

After this your code gets exacted which now registers the call to `'/bar'` and now the request queue looks like this `['/bar']`.
Now your **second** call to `server.respond()` again responds to all the request in queue which is `['/bar']`.

Does this help?

**Comment by isterkebab** [comment]
Ah got it, thanks.

Is there any way to access the queue so that I know if another `server.respond()` call is required?

**Comment by gyandeeps** [comment]
I don't think so but not sure tho.

**Comment by isterkebab** [comment]
Allright, thanks a lot for your time!

**Comment by isterkebab** [comment]
Just for someone else running in to the same problem, this seems to do the trick:

    while(this.server.queue.length > 0){
        this.server.respond();
    }
