### ISSUE TITLE
[Question] Sandbox does not mirror global sinon instance. Is this expected behavior?

### ISSUE THREAD

**Issue by fearphage** [cjohansen/Sinon.JS#828]
There are several things missing or renamed in the sandbox. Is this intentional/expected behavior?

- [ ] `sinon.fakeServer.create()` -> `sandbox.useFakeServer()`
- [ ] `sinon.fakeServerWithClock.create()` -> `sandbox.???`
- [ ] `sinon.createStubInstance(...)` -> `sandbox.???`
- [x] `sinon.assert` -> `sandbox.???`
- [ ] `sinon.FakeXMLHttpRequest.useFilters`
- [ ] `sinon.FakeXMLHttpRequest.addFilter`

**Comment by mantoni** [comment]
Well, I think the difference in the naming comes from a sandbox "using" something in the sense of adding stuff to the sandbox, whereas the `create` functions return instances that live by themselves.

Sanboxes are mainly used to have automatic "roll back" for things like stubs and timers. For `sinon.createStubInstance` and `sinon.assert` there is nothing to revert, which is why there is no such implementation on the sandbox.

**Comment by fearphage** [comment]
Does the sandbox have a reference to the "global" sinon? Otherwise a user has to provide both to a test/class/method. That seems suboptimal from a testing perspective.

**Comment by mantoni** [comment]
A sandbox creates fake servers and timers for you. I believe there is a misunderstanding here. Please refer to the docs: http://sinonjs.org/docs/#sandbox

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by asgerhallas** [comment]
I too see this is an issue. In my situation the test infrastructure creates a sandbox and passes this to the individual tests, which can be assured that everything stubbed, spyed or mocked will be restored. We don't allow global access to sinon, because we want to ensure that nothing leaks. 

But when we can't have access to the non-leaking methods of sinon through the sandbox, it means we can't do this :)

**Comment by papandreou** [comment]
I've also run into this issue, but from a slightly different angle. The [Unexpected-sinon](http://unexpected.js.org/unexpected-sinon/) module supports asserting on the complete "timeline" of calls, and because Sinon doesn't keep a global registry of all fakes that have been created, Sandboxes are the best option for not having to list all the spy instances when asserting. That's all fine until a stub instance is in play because it doesn't show up in `sandbox.fakes`  due to `createStubInstance` not being present as a method on the sandbox.

Like @fearphage and @asgerhallas I think this feels like an odd omission that causes actual problems.

@mantoni, could you please reassess whether you might have closed this feature request a bit too quickly? I'll happily provide a PR, but would like a "go ahead" first :)

**Comment by mantoni** [comment]
I don't understand why `createStubInstance` should register in a sandbox? The only reason for the `fakes` being registered is to `restore` them in one call. There is nothing to restore in case of a stub instance.

**Comment by papandreou** [comment]
@mantino,

> The only reason for the `fakes` being registered is to restore them in one call

To me `fakes` serves another purpose. The unexpected-sinon plugin has some fancy assertions that allow you to assert on the entire timeline of spy/stub calls by specifying a function that performs the calls. That way you can make a statement about the expected parameters as well as the order of the calls (like `sinon.assert.callOrder`) at the same time. Here's an example:

```js
var foo = sinon.spy().named('foo');
var bar = sinon.spy().named('bar');
foo(1);
bar(2);
foo(3);
 
expect([foo, bar], 'to have all calls satisfying', () => {
    foo(1);
    foo(3);
    bar(2);
}); 
```

The above assertion fails because `foo(3);` and `bar(2);` have been swapped.

I've found this pattern very compact and effective, and it allows the assertion library to render very to-the-point diffs when something is wrong.

The main drawback of the above syntax is that since sinon (unlike testdouble for example) doesn't have a global registry of the spies that have been created, this family of assertions need you to either name all the spies/stubs (the `[foo, bar]` array) or provide a sandbox, which implicitly "selects all". It's down to some implementation details (https://github.com/unexpectedjs/unexpected-sinon/issues/28). I've tried a bunch of things, but fundamentally I cannot record the spy calls performed during the function without knowing the spy etc. instances beforehand.

... Back to your point about `sandbox.fakes` only existing so that the spies can easily be restored -- I'm aware that the property is not documented, but I had concluded that because eg.:

```js
var sandbox = sinon.sandbox.create();
var mySpy = sandbox.spy().named('mySpy');
```

... adds `mySpy` to `sandbox.fakes` even though that doesn't need to be restored either, I assumed `sandbox.fakes` would contain all fakes created through the sandbox. That was before I learned about `sinon.createStubInstance`, though.

I really think it's quite reasonable (in "least surprise" terms) to expect that:

* A `sandbox` has an API that mirrors that of the main library, at least wrt. the ability to create different kinds of stubs/spies/"stub instances"
* That all fakes created through the sandbox show up in `sandbox.fakes`, not just the ones that need cleanup

**Comment by mantoni** [comment]
You are relying on internals that may be removed or changed in any patch release. If you want to assert call order, you can use `sinon.assert.callOrder(spy1, spy2, ...)`, which reads better.

A global registry will have very confusing side effects when your test framework executes tests concurrently. It has always been a conscious design decision to not have any global state in Sinon.

Anyhow, we already expose some of the Sinon API on sandboxes, like `match` ([see here](https://github.com/sinonjs/sinon/blob/6eed95876c8ee612948fc1f809af48f79d42cd3c/lib/sinon/sandbox.js#L141)). I'm not sure what the other @sinonjs/sinon-core maintainers think about adding `createStubInstance` for convenience – I don't have any argument against that. But it would certainly just be a reference to `sinon.createStubInstance` and it would not modify the sandbox internal `fakes`.

**Comment by papandreou** [comment]
> You are relying on internals that may be removed or changed in any patch release.

Yes, I guess I'm implicitly arguing that `sandbox.fakes` should be added to the public API because of my use case.

> If you want to assert call order, you can use sinon.assert.callOrder(spy1, spy2, ...), which reads better.

Obviously I disagree, otherwise I wouldn't have made my alternative implementation :). `sinon.assert.callOrder` is not as expressive (doesn't allow you to specify which parameters were associated with the calls), and its behavior isn't well defined in cases where multiple calls to the one spy are interleaved with calls to the others. At best, it's underspecified.

Anyway, I mostly explained my use case so you would know what my background for wanting the list of fakes, not to ask for feedback wrt. my API, and not to talk about `sinon.assert.callOrder`, for that matter.

> A global registry will have very confusing side effects when your test framework executes tests concurrently

Yes,  but that's where a per-test sandbox comes into play. I'm not arguing that sinon should have a global "catch all" sandbox.

> But it would certainly just be a reference to sinon.createStubInstance and it would not modify the sandbox internal `fakes`.

I don't understand why you'd insist on that, but okay. Let's hear what the other maintainers think.

**Comment by mantoni** [comment]
I'm still not convinced that `sinon.assert.callOrder` does not catch your use case. Consider this:

`sinon.assert.callOrder(spy1.withArgs('a'), spy2.withArgs('b'))`.

**Comment by papandreou** [comment]
> `sinon.assert.callOrder(spy1.withArgs('a'), spy2.withArgs('b'))`

I didn't know about that syntax, I agree that it does appear to partially cover my use case.

However, fundamentally I'm not really interested in using Sinon's built-in assertions, only its implementation of fake objects. I'd rather use a dedicated assertion library, so I don't get confused about exactly which semantics apply. I'm aware that eg. sinon-chai is only a thin wrapper around sinon's own assertions, but fully taking over the semantics has a lot of advantages wrt. consistency. Consider a test that uses supertest, sinon, and chai -- there's a lot of mental overhead in juggling the different assertion semantics of each library.

**Comment by mantoni** [comment]
That is quite understandable. I try to reduce mental overhead where possible too. If you want to use a different assertion library, you can put `withArgs` to use like this:

```js
var assert = require('assert');

assert(spy1.withArgs('a').calledBefore(spy2.withArgs('b')));
```

(See http://sinonjs.org/docs/#spies-api)

If you're using Chai, the [sinon-chai](https://github.com/domenic/sinon-chai) project exposes `calledBefore` and `calledAfter`. Maybe that is a better fit then.

**Comment by papandreou** [comment]
I use (and contribute to) unexpected and unexpected-sinon. Most of the crazy things I'm talking about have already been built, eg. http://unexpected.js.org/unexpected-sinon/assertions/spy/to-have-calls-satisfying/ :)
